package com.shashi.srv;

import java.io.IOException;
import java.io.InputStream;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.servlet.http.Part;

import com.shashi.beans.ProductBean;
import com.shashi.service.impl.ProductServiceImpl;

@WebServlet("/AddProductSrv")
@MultipartConfig(maxFileSize = 16177215)
public class AddProductSrv extends HttpServlet {
    private static final long serialVersionUID = 1L;

    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession();
        String userType = (String) session.getAttribute("usertype");
        String userName = (String) session.getAttribute("username");
        String password = (String) session.getAttribute("password");

        // Access Checks
        if (userType == null || !userType.equals("admin")) {
            response.sendRedirect("login.jsp?message=Access Denied!");
            return;
        }

        if (userName == null || password == null) {
            response.sendRedirect("login.jsp?message=Session Expired, Login Again to Continue!");
            return;
        }

        // Retrieve form data
        String prodName = request.getParameter("name");
        String prodType = request.getParameter("type");
        String prodInfo = request.getParameter("info");

        double prodPrice = 0;
        int prodQuantity = 0;
        double pdiscount = 0.0;

        try {
            prodPrice = Double.parseDouble(request.getParameter("price"));
            prodQuantity = Integer.parseInt(request.getParameter("quantity"));
        } catch (Exception e) {
            RequestDispatcher rd = request.getRequestDispatcher("addProduct.jsp?message=Invalid numeric input!");
            rd.forward(request, response);
            return;
        }

        // Discount field (optional in your JSP)
        try {
            if (request.getParameter("discount") != null)
                pdiscount = Double.parseDouble(request.getParameter("discount"));
        } catch (Exception ignored) {
            pdiscount = 0.0;
        }

        // Image upload
        Part imagePart = request.getPart("image");
        InputStream prodImage = imagePart != null ? imagePart.getInputStream() : null;

        // Build ProductBean
        ProductBean product = new ProductBean();
        product.setProdId(null); // auto-generated by ProductServiceImpl via IDUtil
        product.setProdName(prodName);
        product.setProdType(prodType);
        product.setProdInfo(prodInfo);
        product.setProdPrice(prodPrice);
        product.setProdQuantity(prodQuantity);
        product.setPdiscount(pdiscount);
        product.setProdImage(prodImage);

        // Call ProductServiceImpl
        ProductServiceImpl productService = new ProductServiceImpl();
        String status = productService.addProduct(product);

        // Return to JSP with status message
        RequestDispatcher rd = request.getRequestDispatcher("addProduct.jsp?message=" + status);
        rd.forward(request, response);
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        doGet(request, response);
    }
}
